version: 1.0.0

externals:
  - type: script
    uri: //onepaas.oss-cn-beijing.aliyuncs.com/antd/antd.min.js
  - type: style
    uri: //onepaas.oss-cn-beijing.aliyuncs.com/antd/antd.min.css

pages:
  - name: realms
    path: /realms
    components:
      - name: nav-layout
        type: uri
        uri: http://oss.onelaas.com/ux/lnm-nav-layout/1.1.3/dist/main-1.1.3.min.js
        path: '@lnm/nav-layout'
      - name: form
        type: uri
        uri: http://oss.onelaas.com/ux/lnm-form/1.1.2/dist/main-1.1.2.min.js
        path: '@lnm/form'
    layout:
      name: nav-layout
      statics:
        logoSrc: https://circleci.com/docs/assets/img/logos/logo-wordmark.svg
        navType: slot
        activeNav: access
        activeMenu: realms
        contentBox:
          padding: '18px 24px'
      slots:   
        - name: datatable
          slot: realms
          statics:
            size: small
            pageStart: -1
            detailParamKey: realmId
            header:
              showBtn: true
              btnText: 新增
              title: Realms
          metadata-dep: realms
          links:
            - detail: realms-entities
