version: 1.0.0

resources:
  - name: fomr-detail-fields
    type: restful
    uri: http://39.105.230.7/mock/5f642d3ba107ca0020321882/example/form-detail-fields
  - name: form-detail
    type: restful
    uri: http://39.105.230.7/mock/5f642d3ba107ca0020321882/example/form-detail
  - name: table-data
    type: restful
    uri: http://39.105.230.7/mock/5f642d3ba107ca0020321882/example/table
  - name: table-columns
    type: restful
    uri: http://39.105.230.7/mock/5f642d3ba107ca0020321882/example/table-columns
  - name: form
    type: restful
    uri: http://39.105.230.7/mock/5f642d3ba107ca0020321882/example/form
  - name: detail-id
    type: query
    key: id 
  - name: nav
    type: static
    value:
      - key: 基础服务
        label: infras
        path: /base
      - key: 管理
        label: mange
        path: /mange
  - name: menu
    type: static
    value:
      - key: 基础服务
        label: infras
        path: /base
      - key: 管理
        label: mange
        path: /mange

authorization:
  type: jwt
  key: access
  unlogin:
    redirect: login

externals:
  - type: script
    uri: //onepaas.oss-cn-beijing.aliyuncs.com/antd/antd.min.js
  - type: style
    uri: //onepaas.oss-cn-beijing.aliyuncs.com/antd/antd.min.css

components:
  - name: nav-layout
    source: 
      type: uri
      uri: //onepaas.oss-cn-beijing.aliyuncs.com/ux/lnm-nav-layout/1.0.0/dist/main-1.0.0.min.js
      path: '@lnm/nav-layout'
  - name: login
    source: 
      type: uri
      uri: //onepaas.oss-cn-beijing.aliyuncs.com/ux/lnm-login/1.0.1/dist/main-1.0.1.min.js
      path: '@lnm/login'
  - name: 'datatable'
    source: 
      type: uri
      uri: //onepaas.oss-cn-beijing.aliyuncs.com/ux/lnm-table/1.0.1/dist/main-1.0.1.min.js
      path: '@lnm/table'
  - name: 'nav'
    source: 
      type: local
      path: antd.Menu
  - name: 'menu'
    source: 
      type: local
      path: antd.Menu

pages:
  - name: home
    path: /home
    layout:
      name: nav-layout
      statics:
        logoSrc: https://circleci.com/docs/assets/img/logos/logo-wordmark.svg
      resources:
        - nav
        - leftMenu: menu
    components:
      - name: datatable
        slot: content
        resources:
          - dataSource: table-data
          - columns: table-columns
        links:
          - detail: one-detail

  - name: login
    path: /
    components:
      - name: login
        slot: content
        resources:
          - form
        links:
          - home
  
  - name: one-detail
    path: /detail-form
    layout:
      name: nav-layout
      statics:
        logoSrc: https://circleci.com/docs/assets/img/logos/logo-wordmark.svg
    query:
      - id 
    components:
      - name: form
        slot: content
        resources:
          - data: form-detail
          - fields: fomr-detail-fields
          - id: detail-id
        links:
          - back: home
       
